import rethinkdb as r
import json
from datetime import datetime, tzinfo

conn = r.connect()
conn.use("ygo")



# pack list before processing
# packnames = [
#     {"pack": 'Absolute Powerforce', "release": datetime.strptime("02, 16, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Abyss Rising', "release": datetime.strptime("11, 9, 2012", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Ancient Prophecy', "release": datetime.strptime("09, 1, 2009", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Ancient Sanctuary', "release": datetime.strptime("06, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Battles of Legend: Light\'s Revenge', "release": datetime.strptime("07, 7, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Battles of Legend: Relentless Revenge', "release": datetime.strptime("06, 29, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Breakers of Shadow', "release": datetime.strptime("1, 15, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Circuit Break', "release": datetime.strptime("10, 20, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Clash of Rebellions', "release": datetime.strptime("08, 7, 2015", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Code of the Duelist', "release": datetime.strptime("08, 4, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Cosmo Blazer', "release": datetime.strptime("1, 25, 2013", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Crimson Crisis', "release": datetime.strptime("03, 3, 2009", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Crossed Souls', "release": datetime.strptime("05, 15, 2015", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Crossroads of Chaos', "release": datetime.strptime("11, 18, 2008", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Cyberdark Impact', "release": datetime.strptime("11, 15, 2006", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Cybernetic Horizon', "release": datetime.strptime("07, 27, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Cybernetic Revolution', "release": datetime.strptime("08, 17, 2005", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Beginning 1', "release": datetime.strptime("10, 12, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Beginning 2', "release": datetime.strptime("07, 27, 2005", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Crisis', "release": datetime.strptime("12, 1, 2003", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Legends', "release": datetime.strptime("11, 21, 2008", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Revelation Volume 4', "release": datetime.strptime("11, 14, 2007", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dark Saviors', "release": datetime.strptime("05, 25, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Destiny Soldiers', "release": datetime.strptime("11, 18, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dimension of Chaos', "release": datetime.strptime("11, 6, 2015", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dragons of Legend', "release": datetime.strptime("04, 25, 2014", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Dragons of Legend 2', "release": datetime.strptime("1, 1, 2012", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Duelist Alliance', "release": datetime.strptime("08, 15, 2014", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Duelist Revolution', "release": datetime.strptime("08, 17, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Elemental Energy', "release": datetime.strptime("11, 16, 2005", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Enemy of Justice', "release": datetime.strptime("05, 17, 2006", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Exclusive Pack', "release": datetime.strptime("08, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Extreme Force', "release": datetime.strptime("02, 2, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Extreme Victory', "release": datetime.strptime("05, 10, 2011", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Flames of Destruction', "release": datetime.strptime("05, 4, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Flaming Eternity', "release": datetime.strptime("03, 1, 2005", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Force of the Breaker', "release": datetime.strptime("05, 16, 2007", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Fusion Enforcers', "release": datetime.strptime("02, 24, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Galactic Overlord', "release": datetime.strptime("05, 8, 2012", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Generation Force', "release": datetime.strptime("08, 16, 2011", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Gladiator\'s Assault', "release": datetime.strptime("11, 14, 2007", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Hidden Arsenal', "release": datetime.strptime("11, 10, 2009", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Hidden Arsenal 2', "release": datetime.strptime("07, 20, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Hidden Arsenal 3', "release": datetime.strptime("12, 7, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Hidden Arsenal 4: Trishula\'s Triumph', "release": datetime.strptime("04, 19, 2011", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'High-Speed Riders', "release": datetime.strptime("10, 2, 2015", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Invasion of Chaos', "release": datetime.strptime("03, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Invasion: Vengeance', "release": datetime.strptime("11, 4, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Judgment of the Light', "release": datetime.strptime("08, 9, 2013", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Labyrinth of Nightmare', "release": datetime.strptime("03, 1, 2003", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Legacy of Darkness', "release": datetime.strptime("06, 6, 2003", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Legend of Blue Eyes White Dragon', "release": datetime.strptime("12, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Legendary Duelists', "release": datetime.strptime("09, 8, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Legendary Duelists: Ancient Millennium', "release": datetime.strptime("02, 23, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Legendary Duelists: White Dragon Abyss', "release": datetime.strptime("09, 28, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Light of Destruction', "release": datetime.strptime("05, 13, 2008", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Lord of the Tachyon Galaxy', "release": datetime.strptime("05, 17, 2013", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Magician\'s Force', "release": datetime.strptime("10, 10, 2003", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Maximum Crisis', "release": datetime.strptime("05, 5, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Metal Raiders', "release": datetime.strptime("06, 26, 2002", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Movie Pack', "release": datetime.strptime("08, 13, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Number Hunters', "release": datetime.strptime("07, 12, 2013", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Order of Chaos', "release": datetime.strptime("1, 24, 2012", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Pendulum Evolution', "release": datetime.strptime("06, 23, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Phantom Darkness', "release": datetime.strptime("02, 13, 2008", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Pharaoh\'s Servant', "release": datetime.strptime("10, 20, 2002", "%m, %d, %Y"), "shortname": "TAEV"},
#     {"pack": 'Pharaonic Guardian', "release": datetime.strptime("07, 18, 2003", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Photon Shockwave', "release": datetime.strptime("11, 15, 2011", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Primal Origin', "release": datetime.strptime("05, 16, 2014", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Raging Battle', "release": datetime.strptime("05, 12, 2009", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Raging Tempest', "release": datetime.strptime("02, 10, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Return of the Duelist', "release": datetime.strptime("08, 28, 2012", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Rise of Destiny', "release": datetime.strptime("12, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Secrets of Eternity', "release": datetime.strptime("1, 16, 2015", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Shadow of Infinity', "release": datetime.strptime("02, 18, 2006", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Shadow Specters', "release": datetime.strptime("11, 8, 2013", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Shadows in Valhalla', "release": datetime.strptime("08, 17, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Shining Victories', "release": datetime.strptime("05, 6, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Soul Fusion', "release": datetime.strptime("10, 19, 2018", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Soul of the Duelist', "release": datetime.strptime("10, 1, 2004", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Spell Ruler', "release": datetime.strptime("09, 16, 2002", "%m, %d, %Y"), "shortname": "TAEV"},
#     {"pack": 'Spirit Warriors', "release": datetime.strptime("11, 17, 2017", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Stardust Overdrive', "release": datetime.strptime("11, 17, 2009", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Starstrike Blast', "release": datetime.strptime("11, 16, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Storm of Ragnarok', "release": datetime.strptime("02, 8, 2011", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Strike of Neos', "release": datetime.strptime("02, 28, 2007", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Tactical Evolution', "release": datetime.strptime("08, 15, 2007", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'The Dark Illusion', "release": datetime.strptime("08, 5, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'The Duelist Genesis', "release": datetime.strptime("09, 2, 2008", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'The Lost Millennium', "release": datetime.strptime("06, 1, 2005", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'The New Challengers', "release": datetime.strptime("11, 7, 2014", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'The Shining Darkness', "release": datetime.strptime("05, 11, 2010", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'War of the Giants: Round 2', "release": datetime.strptime("1, 17, 2014", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'Wing Raiders', "release": datetime.strptime("02, 12, 2016", '%m, %d, %Y'), "shortname": "TAEV"},
#     {"pack": 'World Superstars', "release": datetime.strptime("04, 17, 2015", '%m, %d, %Y'), "shortname": "TAEV"}]

# grabs shortnames from abbrv file
# y = ""
# file = open("packAbbrv")
# for line in file:
#     for x, value in enumerate(packnames):
#         if packnames[x]["pack"] == line.strip():
#             y = line.strip()
#         elif y == packnames[x]["pack"]:
#             packnames[x]["shortname"] = line.strip()
#             print("%s," % (packnames[x]))
#             y = ""

time = r.make_timezone("-06:00")

packnames = [
    {'pack': 'Absolute Powerforce', 'shortname': 'ABPF', 'release': datetime(2010, 2, 16, 0, 0, 0, 0, time)},
    {'pack': 'Abyss Rising', 'shortname': 'ABYR', 'release': datetime(2012, 11, 9, 0, 0, 0, 0, time)},
    {'pack': 'Ancient Prophecy', 'shortname': 'ANPR', 'release': datetime(2009, 9, 1, 0, 0, 0, 0, time)},
    {'pack': 'Ancient Sanctuary', 'shortname': 'AST', 'release': datetime(2004, 6, 1, 0, 0, 0, 0, time)},
    {'pack': "Battles of Legend: Light's Revenge", 'shortname': 'BLLR', 'release': datetime(2017, 7, 7, 0, 0, 0, 0, time)},
    {'pack': 'Battles of Legend: Relentless Revenge', 'shortname': 'BLRR', 'release': datetime(2018, 6, 29, 0, 0, 0, 0, time)},
    {'pack': 'Breakers of Shadow', 'shortname': 'BOSH', 'release': datetime(2016, 1, 15, 0, 0, 0, 0, time)},
    {'pack': 'Circuit Break', 'shortname': 'CIBR', 'release': datetime(2017, 10, 20, 0, 0, 0, 0, time)},
    {'pack': 'Clash of Rebellions', 'shortname': 'CORE', 'release': datetime(2015, 8, 7, 0, 0, 0, 0, time)},
    {'pack': 'Code of the Duelist', 'shortname': 'COTD', 'release': datetime(2017, 8, 4, 0, 0, 0, 0, time)},
    {'pack': 'Cosmo Blazer', 'shortname': 'CBLZ', 'release': datetime(2013, 1, 25, 0, 0, 0, 0, time)},
    {'pack': 'Crimson Crisis', 'shortname': 'CRMS', 'release': datetime(2009, 3, 3, 0, 0, 0, 0, time)},
    {'pack': 'Crossed Souls', 'shortname': 'CROS', 'release': datetime(2015, 5, 15, 0, 0, 0, 0, time)},
    {'pack': 'Crossroads of Chaos', 'shortname': 'CSOC', 'release': datetime(2008, 11, 18, 0, 0, 0, 0, time)},
    {'pack': 'Cyberdark Impact', 'shortname': 'CDIP', 'release': datetime(2006, 11, 15, 0, 0, 0, 0, time)},
    {'pack': 'Cybernetic Horizon', 'shortname': 'CYHO', 'release': datetime(2018, 7, 27, 0, 0, 0, 0, time)},
    {'pack': 'Cybernetic Revolution', 'shortname': 'CRV', 'release': datetime(2005, 8, 17, 0, 0, 0, 0, time)},
    {'pack': 'Dark Beginning 1', 'shortname': 'DB1', 'release': datetime(2004, 10, 12, 0, 0, 0, 0, time)},
    {'pack': 'Dark Beginning 2', 'shortname': 'DB2', 'release': datetime(2005, 7, 27, 0, 0, 0, 0, time)},
    {'pack': 'Dark Crisis', 'shortname': 'DCR', 'release': datetime(2003, 12, 1, 0, 0, 0, 0, time)},
    {'pack': 'Dark Legends', 'shortname': 'DLG1', 'release': datetime(2008, 11, 21, 0, 0, 0, 0, time)},
    {'pack': 'Dark Revelation Volume 4', 'shortname': 'DR04', 'release': datetime(2007, 11, 14, 0, 0, 0, 0, time)},
    {'pack': 'Dark Saviors', 'shortname': 'DASA', 'release': datetime(2018, 5, 25, 0, 0, 0, 0, time)},
    {'pack': 'Destiny Soldiers', 'shortname': 'DESO', 'release': datetime(2016, 11, 18, 0, 0, 0, 0, time)},
    {'pack': 'Dimension of Chaos', 'shortname': 'DOCS', 'release': datetime(2015, 11, 6, 0, 0, 0, 0, time)},
    {'pack': 'Dragons of Legend', 'shortname': 'DRLG', 'release': datetime(2014, 4, 25, 0, 0, 0, 0, time)},
    {'pack': 'Dragons of Legend 2', 'shortname': 'DRL2', 'release': datetime(2012, 1, 1, 0, 0, 0, 0, time)},
    {'pack': 'Duelist Alliance', 'shortname': 'DUEA', 'release': datetime(2014, 8, 15, 0, 0, 0, 0, time)},
    {'pack': 'Duelist Revolution', 'shortname': 'DREV', 'release': datetime(2010, 8, 17, 0, 0, 0, 0, time)},
    {'pack': 'Elemental Energy', 'shortname': 'EEN', 'release': datetime(2005, 11, 16, 0, 0, 0, 0, time)},
    {'pack': 'Enemy of Justice', 'shortname': 'EOJ', 'release': datetime(2006, 5, 17, 0, 0, 0, 0, time)},
    {'pack': 'Exclusive Pack', 'shortname': 'EP1', 'release': datetime(2004, 8, 1, 0, 0, 0, 0, time)},
    {'pack': 'Extreme Force', 'shortname': 'EXFO', 'release': datetime(2018, 2, 2, 0, 0, 0, 0, time)},
    {'pack': 'Extreme Victory', 'shortname': 'EXVC', 'release': datetime(2011, 5, 10, 0, 0, 0, 0, time)},
    {'pack': 'Flames of Destruction', 'shortname': 'FLOD', 'release': datetime(2018, 5, 4, 0, 0, 0, 0, time)},
    {'pack': 'Flaming Eternity', 'shortname': 'FET', 'release': datetime(2005, 3, 1, 0, 0, 0, 0, time)},
    {'pack': 'Force of the Breaker', 'shortname': 'FOTB', 'release': datetime(2007, 5, 16, 0, 0, 0, 0, time)},
    {'pack': 'Fusion Enforcers', 'shortname': 'FUEN', 'release': datetime(2017, 2, 24, 0, 0, 0, 0, time)},
    {'pack': 'Galactic Overlord', 'shortname': 'GAOV', 'release': datetime(2012, 5, 8, 0, 0, 0, 0, time)},
    {'pack': 'Generation Force', 'shortname': 'GENF', 'release': datetime(2011, 8, 16, 0, 0, 0, 0, time)},
    {'pack': "Gladiator's Assault", 'shortname': 'GLAS', 'release': datetime(2007, 11, 14, 0, 0, 0, 0, time)},
    {'pack': 'Hidden Arsenal', 'shortname': 'HA01', 'release': datetime(2009, 11, 10, 0, 0, 0, 0, time)},
    {'pack': 'Hidden Arsenal 2', 'shortname': 'HA02', 'release': datetime(2010, 7, 20, 0, 0, 0, 0, time)},
    {'pack': 'Hidden Arsenal 3', 'shortname': 'HA03', 'release': datetime(2010, 12, 7, 0, 0, 0, 0, time)},
    {'pack': "Hidden Arsenal 4: Trishula's Triumph", 'shortname': 'HA04', 'release': datetime(2011, 4, 19, 0, 0, 0, 0, time)},
    {'pack': 'High-Speed Riders', 'shortname': 'HSRD', 'release': datetime(2015, 10, 2, 0, 0, 0, 0, time)},
    {'pack': 'Invasion of Chaos', 'shortname': 'IOC', 'release': datetime(2004, 3, 1, 0, 0, 0, 0, time)},
    {'pack': 'Invasion: Vengeance', 'shortname': 'INOV', 'release': datetime(2016, 11, 4, 0, 0, 0, 0, time)},
    {'pack': 'Judgment of the Light', 'shortname': 'JOTL', 'release': datetime(2013, 8, 9, 0, 0, 0, 0, time)},
    {'pack': 'Labyrinth of Nightmare', 'shortname': 'LON', 'release': datetime(2003, 3, 1, 0, 0, 0, 0, time)},
    {'pack': 'Legacy of Darkness', 'shortname': 'LOD', 'release': datetime(2003, 6, 6, 0, 0, 0, 0, time)},
    {'pack': 'Legend of Blue Eyes White Dragon', 'shortname': 'LOB', 'release': datetime(2004, 12, 1, 0, 0, 0, 0, time)},
    {'pack': 'Legendary Duelists', 'shortname': 'LEDU', 'release': datetime(2017, 9, 8, 0, 0, 0, 0, time)},
    {'pack': 'Legendary Duelists: Ancient Millennium', 'shortname': 'LED2', 'release': datetime(2018, 2, 23, 0, 0, 0, 0, time)},
    {'pack': 'Legendary Duelists: White Dragon Abyss', 'shortname': 'LED3', 'release': datetime(2018, 9, 28, 0, 0, 0, 0, time)},
    {'pack': 'Light of Destruction', 'shortname': 'LODT', 'release': datetime(2008, 5, 13, 0, 0, 0, 0, time)},
    {'pack': 'Lord of the Tachyon Galaxy', 'shortname': 'LTGY', 'release': datetime(2013, 5, 17, 0, 0, 0, 0, time)},
    {'pack': "Magician's Force", 'shortname': 'MFC', 'release': datetime(2003, 10, 10, 0, 0, 0, 0, time)},
    {'pack': 'Maximum Crisis', 'shortname': 'MACR', 'release': datetime(2017, 5, 5, 0, 0, 0, 0, time)},
    {'pack': 'Metal Raiders', 'shortname': 'MRD', 'release': datetime(2002, 6, 26, 0, 0, 0, 0, time)},
    {'pack': 'Movie Pack', 'shortname': 'MOV', 'release': datetime(2004, 8, 13, 0, 0, 0, 0, time)},
    {'pack': 'Number Hunters', 'shortname': 'NUMH', 'release': datetime(2013, 7, 12, 0, 0, 0, 0, time)},
    {'pack': 'Order of Chaos', 'shortname': 'ORCS', 'release': datetime(2012, 1, 24, 0, 0, 0, 0, time)},
    {'pack': 'Pendulum Evolution', 'shortname': 'PEVO', 'release': datetime(2017, 6, 23, 0, 0, 0, 0, time)},
    {'pack': 'Phantom Darkness', 'shortname': 'PTDN', 'release': datetime(2008, 2, 13, 0, 0, 0, 0, time)},
    {'pack': "Pharaoh's Servant", 'shortname': 'PSV', 'release': datetime(2002, 10, 20, 0, 0, 0, 0, time)},
    {'pack': 'Pharaonic Guardian', 'shortname': 'PGD', 'release': datetime(2003, 7, 18, 0, 0, 0, 0, time)},
    {'pack': 'Photon Shockwave', 'shortname': 'PHSW', 'release': datetime(2011, 11, 15, 0, 0, 0, 0, time)},
    {'pack': 'Primal Origin', 'shortname': 'PRIO', 'release': datetime(2014, 5, 16, 0, 0, 0, 0, time)},
    {'pack': 'Raging Battle', 'shortname': 'RGBT', 'release': datetime(2009, 5, 12, 0, 0, 0, 0, time)},
    {'pack': 'Raging Tempest', 'shortname': 'RATE', 'release': datetime(2017, 2, 10, 0, 0, 0, 0, time)},
    {'pack': 'Return of the Duelist', 'shortname': 'REDU', 'release': datetime(2012, 8, 28, 0, 0, 0, 0, time)},
    {'pack': 'Rise of Destiny', 'shortname': 'RDS', 'release': datetime(2004, 12, 1, 0, 0, 0, 0, time)},
    {'pack': 'Secrets of Eternity', 'shortname': 'SECE', 'release': datetime(2015, 1, 16, 0, 0, 0, 0, time)},
    {'pack': 'Shadow of Infinity', 'shortname': 'SOI', 'release': datetime(2006, 2, 18, 0, 0, 0, 0, time)},
    {'pack': 'Shadow Specters', 'shortname': 'SHSP', 'release': datetime(2013, 11, 8, 0, 0, 0, 0, time)},
    {'pack': 'Shadows in Valhalla', 'shortname': 'SHVA', 'release': datetime(2018, 8, 17, 0, 0, 0, 0, time)},
    {'pack': 'Shining Victories', 'shortname': 'SHVI', 'release': datetime(2016, 5, 6, 0, 0, 0, 0, time)},
    {'pack': 'Soul Fusion', 'shortname': 'SOFU', 'release': datetime(2018, 10, 19, 0, 0, 0, 0, time)},
    {'pack': 'Soul of the Duelist', 'shortname': 'SOD', 'release': datetime(2004, 10, 1, 0, 0, 0, 0, time)},
    {'pack': 'Spell Ruler', 'shortname': 'SRL', 'release': datetime(2002, 9, 16, 0, 0, 0, 0, time)},
    {'pack': 'Spirit Warriors', 'shortname': 'SPWA', 'release': datetime(2017, 11, 17, 0, 0, 0, 0, time)},
    {'pack': 'Stardust Overdrive', 'shortname': 'SOVR', 'release': datetime(2009, 11, 17, 0, 0, 0, 0, time)},
    {'pack': 'Starstrike Blast', 'shortname': 'STBL', 'release': datetime(2010, 11, 16, 0, 0, 0, 0, time)},
    {'pack': 'Storm of Ragnarok', 'shortname': 'STOR', 'release': datetime(2011, 2, 8, 0, 0, 0, 0, time)},
    {'pack': 'Strike of Neos', 'shortname': 'STON', 'release': datetime(2007, 2, 28, 0, 0, 0, 0, time)},
    {'pack': 'Tactical Evolution', 'shortname': 'TAEV', 'release': datetime(2007, 8, 15, 0, 0, 0, 0, time)},
    {'pack': 'The Dark Illusion', 'shortname': 'TDIL', 'release': datetime(2016, 8, 5, 0, 0, 0, 0, time)},
    {'pack': 'The Duelist Genesis', 'shortname': 'TDGS', 'release': datetime(2008, 9, 2, 0, 0, 0, 0, time)},
    {'pack': 'The Lost Millennium', 'shortname': 'TLM', 'release': datetime(2005, 6, 1, 0, 0, 0, 0, time)},
    {'pack': 'The New Challengers', 'shortname': 'NECH', 'release': datetime(2014, 11, 7, 0, 0, 0, 0, time)},
    {'pack': 'The Shining Darkness', 'shortname': 'TSHD', 'release': datetime(2010, 5, 11, 0, 0, 0, 0, time)},
    {'pack': 'War of the Giants: Round 2', 'shortname': 'BPW2', 'release': datetime(2014, 1, 17, 0, 0, 0, 0, time)},
    {'pack': 'Wing Raiders', 'shortname': 'WIRA', 'release': datetime(2016, 2, 12, 0, 0, 0, 0, time)},
    {'pack': 'World Superstars', 'shortname': 'WSUP', 'release': datetime(2015, 4, 17, 0, 0, 0, 0, time)}]

results = r.table("packlist").insert(packnames).run(conn)
